export const REALTIME_WEBSOCKET_DEFAULT_MAX_FRAME_BYTES = 1024 * 1024;
export const REALTIME_WEBSOCKET_CLOSE_UNSUPPORTED = 4400;
export const REALTIME_WEBSOCKET_CLOSE_POLICY = 4403;
export const REALTIME_WEBSOCKET_CLOSE_TOO_LARGE = 4409;
export const REALTIME_WEBSOCKET_CLOSE_HEARTBEAT_TIMEOUT = 4410;
export const REALTIME_WEBSOCKET_CLOSE_BACKPRESSURE = 4413;
